### ISSUE TITLE
Читаемость кода

### ISSUE THREAD

**Issue by latyschka** [G0r0d0v/OS.Lab1-BBBO-07-19-Gorodov#1]
https://github.com/G0r0d0v/OS.Lab1-BBBO-07-19-Gorodov/blob/2534eae7f2e87f11aa29dbc34f1967ffa0b8db3a/Program.cs#L156
1.Разнесите код по отдельным процедурам. Если количество строк больше 50 в одной процедуре , рекомендуется разнести код по отдельным процедурам. Task1, Task2 and etc....
2. Удалите "висящие" строки, лишние пробелы.
3. Выполните форматирование кода.
4. Добавьте информацию об авторе
5. Добавьте описание вашим процедурам в комментариях

**Comment by buratinoo0** [comment]
Попытался привести все в порядок, работа подписана, процедуры описал

**Comment by latyschka** [comment]
А где обновленный код?

**Comment by buratinoo0** [comment]
в файле program.cs
